Repository IsThereAnyDeal/AugmentedSteam, pull requests merged in 2019-09, with the labels that each got.

#480 Bugfix profile link icons
  css/es_sites_links.css
  img/ico/srcn.png
  js/content/community.js
  js/options/options.js
  options.html
Labels: bug

#512 improve survey.users survey.nobody localization, update zh-TW
  js/content/store.js
  localization/bg/strings.json
  localization/cs/strings.json
  localization/da/strings.json
  localization/de/strings.json
  localization/el/strings.json
  localization/en/strings.json
  localization/es-419/strings.json
  localization/es-ES/strings.json
  localization/fi/strings.json
  localization/fr/strings.json
  localization/hu/strings.json
  localization/it/strings.json
  localization/ja/strings.json
  localization/nl/strings.json
  localization/no/strings.json
  localization/pl/strings.json
  localization/pt-BR/strings.json
  localization/pt-PT/strings.json
  localization/ro/strings.json
  localization/ru/strings.json
  localization/sv-SE/strings.json
  localization/tr/strings.json
  localization/ua/strings.json
  localization/vi/strings.json
  localization/zh-CN/strings.json
  localization/zh-TW/strings.json
Labels: augmentation

#511 Bugfix search term
  js/content/store.js
Labels: bug

#505 Added caching for support info
  js/content/store.js
Labels: augmentation

#506 Extended workshop subscriber
  js/content/common.js
  js/content/community.js
  localization/en/strings.json
  localization/nl/strings.json
Labels: augmentation

#435 Added workshop sorting state
  js/content/community.js
Labels: augmentation

#433 Added barter.vg links
  css/enhancedsteam-firefox.css
  css/enhancedsteam.css
  img/bartervg.png
  js/content/community.js
  js/content/store.js
  js/core.js
  localization/en/strings.json
  localization/nl/strings.json
  options.html
Labels: augmentation, discussion needed

#514 Added quick sell button tooltips
  js/content/community.js
  localization/en/strings.json
  localization/nl/strings.json
Labels: augmentation
