Repository IsThereAnyDeal/AugmentedSteam, pull requests merged in 2019-10, with the labels that each got.

#458 Added multiple guide languages
  css/enhancedsteam.css
  js/content/community.js
  localization/en/strings.json
  localization/nl/strings.json
Labels: augmentation

#470 Add support for community steam links that apply cards images to the link tag
  js/content/community.js
Labels: augmentation

#436 [WIP] IndexedDB support & ITAD integration
  css/enhancedsteam.css
  img/itad.jpg
  js/background/background.js
  js/config.js
  js/content/common.js
  js/content/community.js
  js/content/store.js
  js/core.js
  js/language.js
  js/lib/idb/LICENSE.txt
  js/lib/idb/with-async-ittr.js
  js/lib/webextension-polyfill/LICENSE.txt
  js/lib/webextension-polyfill/browser-polyfill.js
  localization/de/strings.json
  localization/en/strings.json
  manifest.json
  options.html
Labels: WIP, augmentation

#378 Added barter.vg profile link option
  css/es_sites_links-firefox.css
  css/es_sites_links.css
  img/ico/bartervg.png
  js/content/community.js
  js/core.js
  options.html
Labels: augmentation, discussion needed

#592 fix pack breakdown prices
  js/content/store.js
Labels: augmentation

#607 Added market history cache
  js/content/community.js
  localization/en/strings.json
  localization/nl/strings.json
Labels: augmentation
