Repository IsThereAnyDeal/AugmentedSteam, pull requests merged in 2019-11, with the labels that each got.

#515 Changed fullscreen screenshot view at app pages
  css/enhancedsteam.css
  js/content/common.js
  js/content/store.js
Labels: augmentation

#631 fix curator list bug
  css/enhancedsteam.css
Labels: bug

#632 Lowered min-height for artwork
  css/enhancedsteam.css
Labels: bug

#638 Fix horizontal scrollbar on homepage
  js/content/store.js
Labels: bug

#569 improve "Don't automatically filter guides by user language" option
  js/content/community.js
Labels: augmentation

#559 rework OpenCritic right column style
  css/enhancedsteam.css
  img/opencritic.png
  js/content/store.js
Labels: augmentation

#640 Fix and improve apppage customizer
  js/content/store.js
  localization/en/strings.json
Labels: augmentation, bug

#644 Improve regional price mouseover behaviour
  css/enhancedsteam.css
  js/content/store.js
Labels: augmentation

#373 Added friends commenter
  js/content/community.js
  localization/en/strings.json
  localization/nl/strings.json
Labels: augmentation

#605 Fix and simplify opencritic reviews section
  js/content/store.js
Labels: bug

#609 Added invite friends to group back
  js/content/community.js
  localization/en/strings.json
  localization/nl/strings.json
Labels: augmentation

#612 Added horizontal scrolling to store
  js/content/common.js
  js/content/store.js
  js/core.js
  localization/bg/strings.json
  localization/de/strings.json
  localization/en/strings.json
  localization/nl/strings.json
  localization/pt-BR/strings.json
  localization/tr/strings.json
  localization/zh-CN/strings.json
  localization/zh-TW/strings.json
  options.html
Labels: augmentation

#643 Further improve pack breakdown prices
  js/content/store.js
Labels: augmentation

#613 Remove regional price buttons
  js/options/options.js
  localization/en/strings.json
  localization/nl/strings.json
  options.html
Labels: augmentation

#617 Added back to top button
  css/enhancedsteam.css
  js/content/common.js
  js/core.js
  localization/en/strings.json
  localization/nl/strings.json
  options.html
Labels: augmentation

#666 Added shadow to back to top button
  css/enhancedsteam.css
Labels: augmentation

#653 Fixed context menu startup issue
  js/background/background.js
  js/core.js
Labels: bug

#652 Restore missing translation string "lowest_price"
  localization/en/strings.json
Labels: bug

#636 Fix recommended page highlight
  css/enhancedsteam.css
  js/content/common.js
Labels: WIP, bug
